services:
  # Scrapy Application Service
  app:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: scrapy_app
    # Mount the current directory on the host to /usr/src/app in the container
    # This allows for live code changes without rebuilding the image during development
    volumes:
      - .:/usr/src/app
      - ./docker-logs/app:/usr/src/app/logs
    # Define environment variables needed by the application
    environment:
      # Use mongodb://mongo... because 'mongo' is the service name below
      - MONGO_URI=mongodb://mongo:27017/
      - MONGO_DB_NAME=jobs_db
      - MONGO_COLLECTION=raw_jobs
      # Add REDIS_URL here later if you implement the Redis part
      - REDIS_URL=redis://redis:6379/0
      - REDIS_SET_KEY=redis://redis:6379/0
      # - REDIS_URL=redis://redis:6379
    # Make this service depend on the mongo service starting first
    depends_on:
      - mongo
      - redis
    # Keep the container running. We'll use 'docker-compose exec' to run commands.
    # Use tail -f /dev/null for Linux/macOS or timeout /t -1 for Windows base images if needed.
    command: tail -f /dev/null

  # MongoDB Service
  mongo:
    image: mongo:latest # Use the official MongoDB image
    container_name: mongo
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017
    volumes:
      # Use a named volume for persistent MongoDB data
      - mongo_data:/data/db
    # Optional: Add healthcheck for better dependency management if needed

  # Redis Service (Optional - uncomment if/when you implement Redis)
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes: # Optional: Add volume for persistence if needed
      - redis_data:/data

# Define the named volume for MongoDB data persistence
volumes:
  mongo_data:
  redis_data: # Optional: Add if you added the volume above